app/urls.py
from os import name
from django.urls import path
from . import views


app_name = 'app'

urlpatterns = [
    path('', views.inicio,name='inicio'),
    path('login/',views.login_user,name='login'),
    path('private/', views.private,name='private'),
    path('graficos/', views.graficos,name='graficos'),
    path('crearexamen/', views.crear_examen,name='crearexamen'),
    path('<pk>/eliminar/', views.eliminar_examen, name='eliminar_examen'),
    path('examenes/', views.listar_examenes,name='examenes'),
    path('agendar/', views.agendar,name='agendar'),
    path('agregar_usuario/', views.agregar_usuario,name='agregar_usuario'),
    path('<rut>/eliminar_pacientes', views.eliminar_pacientes, name='eliminar_pacientes'),
    path('perfil/', views.perfil, name='perfil'),
]

proyectomedico/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
]
 

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <title>Medical Register</title>
    <meta charset="utf-8">
    <meta name="viewport" 
        content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Loading Bootstrap CSS -->
    <link 
      rel="stylesheet" 
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" 
      integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" 
      crossorigin="anonymous">
    <!--<link href="https://fonts.googleapis.com/css?family=Poiret+One" rel="stylesheet" type="text/css"> -->
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet"> 
    <link  href="{% static 'app/css/style.css' %}" rel="stylesheet">
  </head>
  <body>
    <div class="container-fluid">
      <!-- Navigation Bar -->
      <nav class="navbar navbar-expand-lg navbar-dark fixed-top">
        <a class="navbar-brand" href="{% url 'app:inicio' %}" id="medicalr">MR</a>

        <!-- Navigation Bar Hamburger-->
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navigation"
          aria-expanded="false"
          aria-controls="navigation" 
          aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!-- End Navigation Bar Hamburger -->
        <!-- Navigation Links -->
        <div class="collapse navbar-collapse" id="navigation">
          <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <a 
                  class="nav-link scroll-trigger" 
                  href="#noticia">
                    Noticias
                </a>
              </li>
              <li class="nav-item">
                <a 
                  class="nav-link scroll-trigger" 
                  href="#enlaces"> 
                    Enlaces
                </a>
              </li>
              <li class="nav-item">
                <a
                  class="nav-link scroll-trigger" 
                  href="#contacto">
                    Contacto
                </a>
              </li>
          </ul>
          <!-- Boton login  modal-->
          <div class="text-center">
            <button class="btn btn-outline-success border-dark font-weight-bold text-white my-2 my-sm-0" href="#" data-toggle="modal" data-target="#modalLoginForm">
              Login
            </button>
          </div><!-- Boton login  modal-->
          
        <!-- Navigation Links -->
      </nav>
      <!-- End Navigation Bar -->
      
    {% block jumbotron%}

    {% endblock jumbotron%}
    
    <!-- Noticias-->
    {% block noticias %}

    {% endblock noticias %}
      <!-- End Section: Noticias-->

      <!-- Section: Enlaces -->
    {% block enlaces %}
 
    {% endblock enlaces %}
      <!-- End Section: Enlaces -->

      <!-- Section: Contacto -->
    {% block contacto %}
     
    {% endblock contacto %}
      <!-- End Section: Contacto -->

    {% block footer %}
     
    {% endblock footer %}


     <!-- Login -->
  {% block login %}
    
  {% endblock login %}
  <!-- Login -->


    <!-- jQuery, Popper.js, Bootstrap JS -->
    <script 
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js" 
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" 
      crossorigin="anonymous">
    </script>
    <script 
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" 
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" 
      crossorigin="anonymous">
    </script>
    <script 
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
      integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" 
      crossorigin="anonymous">
    </script>
    {% block script %}
    <!-- <script src="{% static 'app/js/login.js' %}"></script> -->
    
    {% endblock script%}
  </body>
</html>

templates/base_privada.html
{% load static %}
<!doctype html>
<html lang="es">

<head>
    <title>Awakelab Full Stack Python</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Loading Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        
        <link href="https://fonts.googleapis.com/css?family=Poiret+One" 
        rel="stylesheet" type="text/css">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet"> 
    <link  href="{% static 'app/css/style.css' %}" rel="stylesheet">
    <link  href="{% static 'app/css/stylebarra.css' %}" rel="stylesheet">
</head>

<body>
     <!-- Navigation Bar -->
     <nav class="navbar navbar-expand-lg navbar-dark fixed-top">
        <a class="navbar-brand" href="{% url 'app:inicio' %}" id="medicalr">MR</a>

        <!-- Navigation Bar Hamburger-->
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navigation"
          aria-expanded="false"
          aria-controls="navigation" 
          aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!-- End Navigation Bar Hamburger -->
        <!-- Navigation Links -->
        <div class="collapse navbar-collapse" id="navigation">
          <ul class="navbar-nav mr-auto">
             
          </ul>
          <!-- Boton login  modal-->
          <div class="text-center">
            <a href="{% url 'app:inicio' %}" class="btn btn-danger border-dark font-weight-bold text-white my-2 my-sm-0">
              Salir
            </a>
          </div><!-- Boton login  modal-->
          
        <!-- Navigation Links -->
      </nav>
      <!-- End Navigation Bar -->


    <div class="row" id="body-row">
        <!-- Sidebar -->
        <div id="sidebar-container" class="sidebar-expanded d-none d-md-block col-2">
            <div id="perfil" class="d-flex w-100 justify-content-start align-items-center">
               {% block imagenperfil %}

                {% endblock imagenperfil %}
            </div>

            
            <ul class="list-group sticky-top sticky-offset">
                <a href="{% url 'app:private' %}" class="bg-dark list-group-item list-group-item-action">
                 
                    <img class="iconos" src="{% static 'app/img/ficha medica.png' %}">
                    Perfil
                </a>
                <a href="{% url 'app:examenes' %}" class="bg-dark list-group-item list-group-item-action">
                   
                    <img class="iconos" src="{% static 'app/img/medicina.png' %}">
                    examenes
                </a>
                <a href="{% url 'app:agendar' %}" class="bg-dark list-group-item list-group-item-action">
                    
                    <img class="iconos" src="{% static 'app/img/eventos.png' %}">
                     Agendar
                </a>
                <a href="{% url 'app:graficos' %}" class="bg-dark list-group-item list-group-item-action">
                    
                    <img class="iconos" src="{% static 'app/img/estadisticas.png' %}">
                    Estadisticas
                </a>

                 <a href="{% url 'app:agregar_usuario' %}" class="bg-dark list-group-item list-group-item-action">
                   
                    <img class="iconos" src="{% static 'app/img/perfil.png' %}">
                    Agregar usuario
                </a>
            </ul>
        </div>
        <!-- sidebar-container END -->
    
    <!-- MAIN -->
    {% block main %}
       
    
    {% endblock main %}

    </div>
    <!-- body-row END -->

    {% block footer %}
   
    {% endblock footer %}

    

    <!-- jQuery, Popper.js, Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"
			  integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
			  crossorigin="anonymous"></script>
    
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
        </script>
    
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous">
        </script>

    {% block script %}

    {% endblock script %}
</body>

</html>