app/urls.py
from os import name
from django.urls import path
from . import views


app_name = 'app'

urlpatterns = [
    path('', views.inicio,name='inicio'),
    path('login/',views.login_user,name='login'),
    path('private/', views.private,name='private'),
    path('graficos/', views.graficos,name='graficos'),
    path('crearexamen/', views.crear_examen,name='crearexamen'),
    path('<pk>/eliminar/', views.eliminar_examen, name='eliminar_examen'),
    path('examenes/', views.listar_examenes,name='examenes'),
    path('agendar/', views.agendar,name='agendar'),
    path('agregar_usuario/', views.agregar_usuario,name='agregar_usuario'),
    path('<rut>/eliminar_pacientes', views.eliminar_pacientes, name='eliminar_pacientes'),
    path('perfil/', views.perfil, name='perfil'),
]

proyectomedico/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
]
 

app/templates/app/Agregar_usuario.html
{% extends "base_privada.html" %}
{% load static %}


        {% block imagenperfil %}
            <img class="img-fluid rounded" src="{% static 'app/img/profe luis.jpg' %}">
        {% endblock imagenperfil %}

        <!-- MAIN -->
        {% block main %}

        <div class="col py-3">
            <div class="block-header">
                <h2>Agregar Usuario</h2>
                <small class="text-muted"></small>
            </div>

            <div class="row">
                <div class="col-lg-12 col-md12 col-sm-12">
                    <div class="card">
                        <div class="body">
                            <div class="row">
                              <form id="formulario" class="col-md-4" method="POST" novalidate>
                                     {% csrf_token %}
                                        <table>
                                          {{formulario.as_table}}
                                        </table>
                                        
                                        <input type="hidden" name="elemento" value="Paciente">
                                        <button type="submit" class="btn btn-primary mb-3">Agregar</button>
                                     
                                </form>
                                <table class="table col-md-8">
                                    <thead class="thead-inverse">
                                      <tr>
                                        <th>ID</th>
                                        <th>Nombre</th>
                                        <th>Correo</th>
                                        <th>Clave</th>
                                        <th>Rut</th>
                                        <th>Edad</th>
                                        <th>Fecha</th>
                                      </tr>
                                    </thead>
                                    <tbody id="Datos">
                                      {% for pacientes in lista_pacientes %}
                                       <tr>
                                          <td>{{ pacientes.id }}</td>
                                          <td>{{ pacientes.nombre }}</td>
                                           <td>{{ pacientes.correo }}</td>
                                          <td>{{ pacientes.clave }}</td>
                                         
                                          <td>{{pacientes.rut }}</td>
                                          <td>{{pacientes.edad }}</td>
                                          <td>{{pacientes.fecha }}</td>
                                          <td>
                                            <a href="{% url 'app:eliminar_pacientes' rut=pacientes.rut %}" class="btn btn-dark">Borrar</a>
                                          <td/>
                                      <tr>
                                      {% endfor %}
                                    </tbody>
                                  </table>
                            </div>
                        </div>
                    
                          <div class="modal fade" id="modal-form" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog modal-dialog-centered" role="document">
                              <div class="modal-content">
                               
                              </div>
                            </div>
                          </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <!--row-->
        <!-- Main Col END -->
    </div>
    <!-- body-row END -->
    {% endblock main %}
    
    {%block footer%}
    <footer class="footer fixed.bottom bg-dark text-center">
        <p class="text-muted">&copy; 2020 Awakelab.</p>
        <p class="text-muted">Grupo Full Stack Python</p>
    </footer>
    {% endblock footer %}

 
    {% block script %}   
    <script src="{% static 'app/js/main.js' %}"></script>
    {% endblock script %}
</body>

</html>

app/templates/app/Eliminar_examen_parcial.html
<link rel="stylesheet" 
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" 
      integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" 
      crossorigin="anonymous">
    <!--<link href="https://fonts.googleapis.com/css?family=Poiret+One" rel="stylesheet" type="text/css"> -->
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet"> 


<div class="container">
<div class=row>
  <form method="post" action="{% url 'app:eliminar_examen' pk=pk %}" class="mt-4">
  
  {% csrf_token %}
  
    <h2 class="lead">Estas Seguro que quieres eliminar este examen <strong>?</strong></h2>
  

    <a href="{% url 'app:examenes' %}" class="btn btn-primary">Cerrar</a>
    <button type="submit" class="btn btn-danger">Eliminar</button>

</form>
</div>
</div>

app/templates/app/Examen_parcial.html
 <div class="modal-header border-bottom-0">
    <h5 class="modal-title" id="exampleModalLabel">Ingresar Examen</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
 </button>
</div>

<form method="POST" action="{% url 'app:crearexamen' %}" class="js-create-form" novalidate>
  {% csrf_token %}
  <div class="modal-body">
   {% for field in formulario %}
   
       <div class="form-group{% if field.errors %} has-error{% endif %}">
          <label for="nombre">{{field.label}}</label>
          {{field}}
          {% for error in field.errors %}
            <p class="alert alert-danger mt-2">{{ error }}</p>
          {% endfor %}
       </div>  
       
    {% endfor %} 

  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
    <button type="submit" class="btn btn-primary">Agregar</button>
  </div>
</form>


                    

app/templates/app/Examenes.html
{% extends "base_privada.html" %}
{% load static %}


        {% block imagenperfil %}
            <img class="img-fluid rounded" src="{% static 'app/img/profe luis.jpg' %}">
        {% endblock imagenperfil %}

        <!-- MAIN -->
        {% block main %}

        <div class="col py-3">
            <div class="block-header">
                <h2>Examenes</h2>
                <small class="text-muted"></small>
            </div>

            <div class="row">
                <div class="col-lg-12 col-md12 col-sm-12">
                    <div class="card">
                        <div class="body">
                            <div class="row">
                                <button type="button" id="boton-js" class="btn btn-info mb-4"   data-toggle="modal" data-target="#form" data-url="{% url 'app:crearexamen' %}">
                                    Ingresar Examen
                                </button>  
                                <table class="table" id="tabla-datos">
                                    <thead class="thead-inverse">
                                      <tr>
                                        <th>#</th>
                                        <th>Nombre</th>
                                        <th>Rut</th>
                                        <th>Edad</th>
                                        <th>Fecha</th>
                                        <th>Hemograma</th>
                                        <th>Orina</th>
                                        <th>Colesterolhdl</th>
                                        <th>Colesterolldl</th>
                                        <th>Glucosa</th>
                                      </tr>
                                    </thead>
                                    <tbody>
                                          {% include 'app/Examenes_lista_parcial.html' %}
                                    </tbody>
                                  </table>
                            </div>
                        </div>
                    
                          <div class="modal fade" id="modal-form" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog modal-dialog-centered" role="document">
                              <div class="modal-content">
                               
                              </div>
                            </div>
                          </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <!--row-->
        <!-- Main Col END -->
    </div>
    <!-- body-row END -->
    {% endblock main %}
    
    {%block footer%}
    <footer class="footer fixed.bottom bg-dark text-center">
        <p class="text-muted">&copy; 2020 Awakelab.</p>
        <p class="text-muted">Grupo Full Stack Python</p>
    </footer>
    {% endblock footer %}

 
    {% block script %}   
    <script src="{% static 'app/js/main.js' %}"></script>
    {% endblock script %}
</body>

</html>

app/templates/app/Examenes_lista_parcial.html
{% for examen in lista_examenes %}
  
  <tr>
    <td>{{ examen.id }}</td>
    <td>{{ examen.nombre }}</td>
    <td>{{ examen.rut }}</td>
    <td>{{ examen.edad }}</td>
    <td>{{ examen.examenes.0.fecha }}</td>
    <td>{{ examen.examenes.0.hemograma }}</td>
    <td>{{ examen.examenes.0.orina }}</td>
    <td>{{ examen.examenes.0.colesterolhdl }}</td>
    <td>{{ examen.examenes.0.colesterolldl}}</td>
    <td>{{ examen.examenes.0.glucosa }}</td>
    <td>
      <a href="{% url 'app:eliminar_examen' pk=examen.id %}" class="btn btn-danger btn-sm ">Eliminar</a>
    </td>
  </tr>
{% empty %}
  <tr>
    <td colspan="10" class="text-center bg-warning">No hay examenes</td>
  </tr>
{% endfor %}

app/templates/app/Graficos.html
{% extends "base_privada.html" %}
{% load static %}

        {% block imagenperfil %}
                <img class="img-fluid rounded" src="{% static 'app/img/profe luis.jpg' %}">
         {% endblock imagenperfil %}

        <!-- MAIN -->
        {% block main %}
        <div class="col py-3">
            <div class="block-header">
                <h2>Estadisticas de Examenes</h2>
                <small class="text-muted"></small>
            </div>
        
            <div class="row">
                <div class="col-lg-4 col-md-6 col-sm-12">
                    <h2 class="text-center">Glucosa</h2>
                    <canvas id="glucosa" width="400" height="400"></canvas>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-12">
                    <h2 class="text-center">Hemograma</h2>
                    <canvas id="hemograma" width="400" height="400"></canvas>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-12">
                    <h2 class="text-center">Orina</h2>
                    <canvas id="orina" width="400" height="400"></canvas>
                </div>
            </div>
        </div>
        <!--row--> 
        <!-- Main Col END -->
    </div>
    <!-- body-row END -->
    {%endblock main%}


    {% block footer %}
        <footer class="footer fixed.bottom bg-dark text-center">
            <p class="text-muted">&copy; 2020 Awakelab.</p>
            <p class="text-muted">Grupo Full Stack Python</p>
        </footer>
    {% endblock footer %}

    
    {% block script %}

        <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js"></script>


<script>


const glucosa = document.getElementById('glucosa');
const hemograma = document.getElementById('hemograma');
const orina = document.getElementById('orina');

const dataglucosa = {{data.glucosa | safe }}
const datahemograma = {{data.hemograma | safe }}
const dataorina = {{data.orina | safe }}
const meses = {{labels | safe }}
const barType =  ['bar','line','pie']

function chars(id, datos,dataLabel,dataType){
    var ctx = id.getContext('2d');
     new Chart(ctx, {
        type: dataType,
        data: {
            labels: dataLabel,
            datasets: [{
                label: '% de muestras',
                data: datos,
                backgroundColor: [
                    'rgba(255, 99, 132, 0.2)',
                    'rgba(54, 162, 235, 0.2)',
                    'rgba(255, 206, 86, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)',
                    'rgba(255, 159, 64, 0.2)'
                ],
                borderColor: [
                    'rgba(255, 99, 132, 1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)'
                ],
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            }
        }
    });
}

document.addEventListener("DOMContentLoaded", function () {
   chars(glucosa,dataglucosa,meses,barType[0]);
   chars(hemograma,datahemograma,meses,barType[1]);
   chars(orina,dataorina,meses,barType[2]);

});

</script>

    {% endblock script %}

</body>
</html>

app/templates/app/eliminar_pacientes.html
{% extends "base_privada.html" %}
{% load static %}


        {% block imagenperfil %}
            <img class="img-fluid rounded" src="{% static 'app/img/profe luis.jpg' %}">
        {% endblock imagenperfil %}

        <!-- MAIN -->
        {% block main %}

        <div class="col py-3">
            <div class="block-header">
                <h2>Examenes</h2>
                <small class="text-muted"></small>
            </div>

            <div class="row">
                <div class="col-lg-12 col-md12 col-sm-12">
                    <div class="card">
                        <div class="body">
                            <div class="row">
                                
                                <table class="table">
                                    <thead class="thead-inverse">
                                      
                                      <tr>
                                    <form action="{% url 'app:eliminar_pacientes' rut=rut %}" method="POST">
                                      {% csrf_token %}
                                      <h2>Está seguro de eliminar al paciente con numero de rut = {{rut}}?</h2>
                                      <input type="submit" value='Sí'>
                                      </tr>
                                    </thead>
                                    
                                  </table>
                            </div>
                        </div>
                    
                          <div class="modal fade" id="modal-form" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog modal-dialog-centered" role="document">
                              <div class="modal-content">
                               
                              </div>
                            </div>
                          </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <!--row-->
        <!-- Main Col END -->
    </div>
    <!-- body-row END -->
    {% endblock main %}
    
    {%block footer%}
    <footer class="footer fixed.bottom bg-dark text-center">
        <p class="text-muted">&copy; 2020 Awakelab.</p>
        <p class="text-muted">Grupo Full Stack Python</p>
    </footer>
    {% endblock footer %}

 
    {% block script %}   
    <script src="{% static 'app/js/main.js' %}"></script>
    {% endblock script %}
</body>

</html>

app/templates/app/index.html
{% extends "base.html" %}

{% load static %}

      
      {%block jumbotron%}

      <div class="container-fluid bg-principal" id="principal">
        <div class="row">
          <div class="col-sm-12">
            <div class="jumbotron jumbotron-main">
              <h2>Medical Register</h2>
              <h3>Sistema de registro medico online</h3>
            </div>
          </div>
        </div>
      </div>
      <!-- End Section: Principal -->
      {% endblock jumbotron%}

    {% block noticias %}
      <!-- Section: Noticia -->
      <div class="container-fluid bg-light" id="noticia">
        <div class="row">
          <h3>Noticias</h3>
        </div>
        <div class="row">
          <div id="team-carousel" 
              class="carousel slide" 
              data-ride="carousel" 
              data-interval="3000">
            <div class="carousel-inner" style="padding: 4rem;" role="listbox">
              <div style="height: 400px" class="carousel-item active">
                <img class="d-block img-fluid carousel-img" src="{% static 'app/img/mieltopica.jpg' %}">
                <div class="carousel-caption">
                  La mucositis es una respuesta inflamatoria de las células epiteliales de la mucosa a los efectos citotóxicos de la quimioterapia y la radioterapia. El síntoma principal de la mucositis oral es el dolor oral severamente debilitante. Además aumenta la susceptibilidad a las infecciones, lo que puede ocasionar la muerte del paciente por infecciones y poner en compromiso el tratamiento para el cáncer. Se han usado varios tratamientos para prevenir o reducir la gravedad moderada de la mucositis oral, aunque los resultados no han sido contundentes.
                </div>
              </div>
              <div style="height: 400px" class="carousel-item">
                <img class="d-block img-fluid carousel-img" src="{% static 'app/img/sistemainmunologico.jpg' %}">
                <div class="carousel-caption">
                  En los últimos años, los científicos han descubierto algunos vínculos interesantes entre la inmunidad y la mente. De hecho, una de las moléculas de señalización inmunitaria, o citosinas, que median estos enlaces se llama interleucina-17a (IL-17a)
                </div>
              </div>
              <div style="height: 400px" class="carousel-item">
                <img class="d-block img-fluid carousel-img" src="{% static 'app/img/vph.jpg' %}">
                <div class="carousel-caption">
                  Las células epiteliales receptoras tienen un papel fundamental en el ciclo de los VPH, en cuanto al crecimiento y diferenciación. A través de lesiones, heridas y laceraciones del tejido el virus entra en las células, sobre todo en las capas más profundas del epitelio.
                </div>
              </div>
              <div style="height: 400px" class="carousel-item">
                <img class="d-block img-fluid carousel-img" src="{% static 'app/img/mascarilla.jpg' %}">
                <div class="carousel-caption">
                  Las células epiteliales receptoras tienen un papel fundamental en el ciclo de los VPH, en cuanto al crecimiento y diferenciación. A través de lesiones, heridas y laceraciones del tejido el virus entra en las células, sobre todo en las capas más profundas del epitelio.
                </div>
              </div>
              <div style="height: 400px" class="carousel-item">
                <img class="d-block img-fluid carousel-img" src="{% static 'app/img/hospital.jpg' %}">
                <div class="carousel-caption">
                  Clínica Las Condes continuó mostrando números rojos en el tercer trimestre. Anotó pérdidas por $1.937,8 millones en el tercer trimestre, acumulando en el año un saldo negativo de $12.234,9 millones.              </div>
                </div>
              </div> 
              <div style="height: 400px" class="carousel-item">
                <img class="d-block img-fluid carousel-img" src="{% static 'app/img/jovenes.png' %}">
                <div class="carousel-caption">
                  Las primeras etapas de la pandemia de coronavirus y el primer confinamiento por covid-19 hicieron que la cantidad de jóvenes con ansiedad casi que se duplicara, según un estudio de la Universidad de Bristol.                </div>
              </div>  
            <a class="left carousel-control" 
                href="#team-carousel" 
                role="button" 
                data-slide="prev">
              <span class="icon-prev" aria-hidden="true"></span>
            </a>
            <a class="right carousel-control" 
                href="#team-carousel" 
                role="button" 
                data-slide="next">
              <span class="icon-next" aria-hidden="true"></span>
            </a>
            <ol class="carousel-indicators">
              <li data-target="#team-carousel" 
                  data-slide-to="0" 
                  class="active"></li>
              <li data-target="#team-carousel" 
                  data-slide-to="1"></li>
              <li data-target="#team-carousel" 
                  data-slide-to="2"></li>
              <li data-target="#team-carousel" 
                  data-slide-to="3"></li>
              <li data-target="#team-carousel" 
                  data-slide-to="4"></li>
              <li data-target="#team-carousel" 
                  data-slide-to="5"></li>
            </ol>
          </div>
        </div>
      </div>
    {% endblock noticias %}

    
    {% block enlaces %}

      <div class="container-fluid bg-dark" id="enlaces">
        <div class="row">
            <h3>Enlaces de Interés</h3>
        </div>
        <div class="row">
          <div class="col-md-6 col-sm-12">
            <div class="media">
              <img class="img" src="{% static 'app/img/isapres_720.jpg' %}" 
                  alt="Generic placeholder image">
              <div class="media-body">
                <h5>Isapres</h5>
                <ul>
                  <li>Banmedica <a href="https://www.banmedica.cl/">Ver más</a></li>
                  <li>Nueva Mas Vida <a href="https://www.nuevamasvida.cl/">Ver más</a></li>
                  <li>Colmena <a href="http://www.colmena.cl/">Ver más</a></li>
                  <li>Cruz Blanca <a href="https://www.cruzblanca.cl/">Ver más</a></li>
                  <li>Consalud <a href="https://clientes.consalud.cl/">Ver más</a></li>
                  <li>Vida Tres <a href="https://www.vidatres.cl/">Ver más</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="col-md-6 col-sm-12">
            <div class="media">
              <img class="img" src="{% static 'app/img/ambulancias.png' %}" 
                  alt="Generic placeholder image">
              <div class="media-body">
                <h5>Ambulancias en Convenio</h5>
                <ul>
                  <li>Help <a href="https://www.help.cl/">Ver más</a></li>
                  <li>Unidad Coronaria Movil <a href="https://www.ucmchile.cl/">Ver más</a></li>                
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6 col-sm-12">
            <div class="media">
              <img class="img" src="{% static 'app/img/clinicas.jpg' %}" 
                  alt="Generic placeholder image">
              <div class="media-body">
                <h5>Clinicas en Convenio </h5>
                <ul>
                    <li>Alemana <a href="https://www.clinicaalemana.cl/">Ver más</a></li>
                    <li>las Condes <a href="https://www.clinicalascondes.cl/">Ver más</a></li>
                    <li>Santa Maria <a href="https://www.clinicasantamaria.cl/">Ver más</a></li>
                    <li>U andes <a href="https://www.clinicauandes.cl/">Ver más</a></li>
                    <li>Davila <a href="https://www.davila.cl/">Ver más</a></li>
                    <li>Indisa <a href="https://www.indisa.cl/">Ver más</a></li>
                    <li>UC Christus <a href="https://www.ucchristus.cl/">Ver más</a></li>
                    <li>Redsalud <a href="https://www.redsalud.cl/">Ver más</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="col-md-6 col-sm-12">
            <div class="media">
              <img class="img-2" src="{% static 'app/img/fonasa.jpg' %}" 
                  alt="Generic placeholder image">
              <div class="media-body">
                <h5>Fonasa</h5>
                <ul>
                  <li>Fonasa <a href="https://www.fonasa.cl/">Ver más</a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      {% endblock enlaces %}

      {% block contacto %}
      <div class="container-fluid bg-light" id="contacto">
        <div class="row">
          <h1>Contáctanos</h1>
        </div>
        <div class="row justify-content-center align-items-center h-100">
          <div class="col-sm-6" id="contact-form">
            <form>
              <div class="form-group">
                <label for="contact-name"><h2>Nombre</h2></label>
                <input type="text" class="form-control" id="contact-name" 
                    placeholder="Tu Nombre">
              </div>
              <div class="form-group">
                <label for="contact-email"><h2>Email</h2></label>
                <input type="email" class="form-control" id="contact-email" 
                    placeholder="Tu Email">
              </div>
              <div class="form-group">
                <label for="contact-msg"><h2>Mensaje</h2></label>
                <textarea class="form-control" id="contact-msg" 
                    placeholder="Tu Mensaje" rows="4"></textarea>
              </div>
              <div class="btn-group">
                <button type="button" class="btn btn-outline-secondary">Enviar</button>
                <button type="button" class="btn btn-outline-secondary">Limpiar</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    {% endblock contacto %}

    {% block footer %}
      <footer class="footer bg-dark text-center">
        <p class="text-muted">&copy; 2020 Awakelab.</p>
        <p class="text-muted">Grupo Full Stack Python</p>
      </footer>
    {% endblock footer %}

         <!-- Login -->
     {% block login %}

        <!-- MODAL FORMS -->
      <div class="modal" id="profile-modal" role="dialog">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal"
                aria-label="Close"><span aria-hidden="true">&times;</span>
              </button>
              <p class="modal-title" id="profile-modal-label">Perfil</p>
            </div>
              <div class="modal-body">
                Perfil
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-success">Guardar</button>
                <button type="button" 
                    class="btn btn-secondary" 
                    data-dismiss="modal">Cancelar</button>
              </div>
          </div>
      </div>
      </div>
      <div class="modal" id="settings-modal" role="dialog">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" 
                aria-label="Close"><span aria-hidden="true">&times;</span>
              </button>
              <p class="modal-title" id="settings-modal-label">Configuración</p>
            </div>
            <div class="modal-body">
              Configuración
            </div>
            <div class="modal-footer">
              <button type="button" 
                  class="btn btn-success">Guardar</button>
              <button type="button" 
                  class="btn btn-secondary" 
                  data-dismiss="modal">Cancelar</button>
            </div>
          </div>
        </div>
      </div>
      <!-- END MODAL FORMS -->
    </div>  

     <div class="modal fade" id="modalLoginForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header text-center">
            <h4 class="modal-title w-100 font-weight-bold">Sign in</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>

           <form action="{% url 'app:login' %}" method="POST" novalidate >
           {% csrf_token %}
          <div class="modal-body mx-3">
               {{formulario.as_table}}
             {% comment %} <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Email</label>
                <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
              </div>
              <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">Contraseña</label>
                <input type="password" class="form-control" id="exampleInputPassword1">
              </div>  {% endcomment %}
          </div>
          <div class="modal-footer d-flex justify-content-center">
            <button type="submit" class="btn btn-primary">Login</button>
          </div>
           </form>
        </div>
      </div>
    </div>
  </div>
  {% endblock login %}


  {% block script %}
  
  {% endblock script %}

app/templates/app/perfil_form.html
<form method="POST" action="{% url 'app:perfil' %}">
 {% csrf_token %}
 <div class="container"> 
        <h4 class="text-center">Cambiar Perfil<h4>
        <div class="input-group  mb-3"> 
           <select  class="form-control" name="usuarios">
            {% for usuario in perfiles %}
              
                <option value={{usuario.id}}>{{ usuario.nombre }}</option>
            
            {% endfor %}
               
                <option selected="selected"> Sin Perfil </option>
            
            </select> 
            <div class="input-group-append"> 
                <button type="submit" value="cargar usuarios" class="btn btn-primary">Enviar</button>
            </div> 
          
        </div> 
</div> 
  
</form>